IF OBJECT_ID('CHANGE_CELL') IS NOT NULL
    DROP PROCEDURE CHANGE_CELL;
GO

CREATE PROCEDURE CHANGE_CELL
    @pCellID INT,
    @pColour NVARCHAR(10)
AS
BEGIN
    BEGIN TRY
        UPDATE CELLS
        SET Colour = @pColour
        WHERE CellID = @pCellID 
    END TRY
    BEGIN CATCH
    END CATCH
END
GO